More Omnipod updates & cleanup
MilosKozak/AndroidAPS pull request #2945
Opened 2020-09-01 21:02 UTC by bartsopers

2020-09-05 23:11 UTC, AdrianLxM requested changes
Nice large PR :)

I have a few comments in the general part of this PR.
I only reviewed the parts that intertwine with the rest of the app. The core omnipod packages I did not have a deeper look.

2020-09-05 23:11 UTC, AdrianLxM commented on omnipod/src/main/java/info/nightscout/androidaps/plugins/pump/omnipod/dagger/OmnipodModule.kt
> +    @ContributesAndroidInjector abstract fun omnipodPumpPlugin(): OmnipodPumpPlugin
This is a workaround until the plugin is ready?

2020-09-05 23:35 UTC, AdrianLxM commented
As I don't want to force my opinion on how `lateinit` (avoid unless really necessary ;) ): Here are my ideas as PR back to your branch: https://github.com/AAPS-Omnipod/AndroidAPS/pull/166

Feel free to use that - or discard it.

2020-09-06 13:20 UTC, bartsopers commented on omnipod/src/main/java/info/nightscout/androidaps/plugins/pump/omnipod/dagger/OmnipodModule.kt
> +    @ContributesAndroidInjector abstract fun omnipodPumpPlugin(): OmnipodPumpPlugin
What do you mean?

2020-09-06 13:35 UTC, bartsopers commented on app/src/main/java/info/nightscout/androidaps/queue/commands/CommandStartPump.kt
> +            if (profileFunction.getProfile() != null) {
I decided to just pass the profile, even if it's null, as AapsOmnipodManager will handle a null profile and show a notification.

2020-09-06 13:35 UTC, bartsopers commented on core/src/main/java/info/nightscout/androidaps/plugins/general/overview/notifications/Notification.java
> +    public static final int OMNIPOD_POD_SUSPENDED = 61;
Done!

2020-09-06 13:36 UTC, bartsopers commented on core/src/main/java/info/nightscout/androidaps/utils/textValidator/ValidatingEditTextPreference.kt
> +    private lateinit var validatorParameters: DefaultEditTextValidator.Parameters
Merged your PR so this has been fixed

2020-09-06 13:36 UTC, bartsopers commented on omnipod/src/test/java/info/nightscout/androidaps/plugins/pump/omnipod/manager/AapsPodStateManagerTest.java
> -    RxBusWrapper rxBus = new RxBusWrapper();
I changed this to just instantiating RxBusWrapper

2020-09-06 13:37 UTC, bartsopers commented on core/src/main/java/info/nightscout/androidaps/utils/textValidator/DefaultEditTextValidator.kt
> +    class Parameters {
Merged your PR so this has been fixed

2020-09-06 14:24 UTC, AdrianLxM approved these changes
LGTM!

2020-09-08 14:20 UTC, merged